### ISSUE TITLE
InvalidArgumentException when composer requiring

### ISSUE THREAD

**Issue by futurewebsites** [cwsdigital/twill-metadata#3]
[InvalidArgumentException]
  Could not find a matching version of package cwsdigital/twill-metadata. Che
  ck the package spelling, your version constraint and that the package is av
  ailable in a stability which matches your minimum-stability (dev).

Laravel 8
PHP 8.0.0
Twill 2.x

**Comment by futurewebsites** [comment]
Is this maintained?

**Comment by chrispymm** [comment]
Hi, thanks for raising the issue.

This package was built for our Twill projects at the agency, it is mainatined we just haven't started a new Twill project for a good few months now.

I've had a look into this issue for you, and realised that I've never actually published this package to packagist which is why composer require doesn't work for you. 

We only use this package from within our own twill base repo, which lists this repo in it's sources.  

So to resolve the issue you can simply add the following into your composer.json
```
"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:cwsdigital/twill-metadata.git"
        }
    ],
```

I'll look at getting this published onto packagist later this week too.

**Comment by chrispymm** [comment]
Package has now been pulished on packagist so `composer require cwsdigital/twill-metadata` is now working.

Succesfully ranc omposer require for the package in new laravel project, with the latest version of twill.

**Comment by futurewebsites** [comment]
brilliant thank you :)
