### ISSUE TITLE
Undefined method metadata

### ISSUE THREAD

**Issue by csikoszoltan** [cwsdigital/twill-metadata#9]
Hi!

I started to use your Twill base repo but when i'm trying to create an Article I get the following error:
_Call to undefined method App\Models\Article::metadata()_

This only happens at the articles, everything else is working fine.

I tried to dig in in the metadata repo but unfortunately couldn't fix it.
Look like the error is in the HandleMetadata.php line 30.

Any idea how to fix this?

Thanks for your hard work on both repos! :)

**Comment by chrispymm** [comment]
Hi there,

Glad you're finding the repos useful.  

Just had a quick look at your issue, and it looks like the `HasMetadata` trait is missing on the Article model in cws-twill-base. So I think your issue is there rather than in this repo.

Just as an FYI, the twill-base hasn't been updated in a while - I've been doing a lot of work around it in the last couple of weeks, completely refactoring it to use Twill Capsules.  

The Metadata repo is much more up to date, and it's had a lot of work done on it recently.  So the twill-base actually pulls in a really old version of twill-metadata using the github repo.  To solve this, you could run:

`composer remove cwsdigital/twill-metadata`

Then remove lines 10-13 of the composer.json
```
        {
            "type": "vcs",
            "url": "git@github.com:cwsdigital/twill-metadata.git"
        }
```

Then **ensuring you've read the upgrade notes** in the readme of twill-metadata repo, you can

`composer require cwsdigital/twill-metadata`

Pinning your version to either 1.0.x  or 1.1.x depending on whether you have existingtransaltions you want to keep or not.

**Comment by csikoszoltan** [comment]
Thanks, adding HasMetadata trait solved my issue. :)
Will you update the twill-base anytime soon?

**Comment by chrispymm** [comment]
👍 Great.  Glad it solved it for you.  I've just merged a quick PR that adds it in too 🙂

Yeah.  It should be getting updated this week or next.  We've got a bunch of new projects about to kick off, that I want to use the updated base for.

As I hinted though, it will likely work a bit differently.  The base will likely have very little in, it will be a wrapper around a bunch of Twill Capsules which will all live in their own repos, and then can be installed within the base.  So it may be that for people external to our org you just install the individual capsules into your own project rather than using the base repo directly.
